### ISSUE TITLE
`cargo deb` out of date for systemd integration

### ISSUE THREAD

**Issue by username223** [ebbflow-io/cargo-deb-armv7-debian#1]
The installed version of `cargo deb` (1.26.0) does not support automatic systemd integration, leading to an error and exit(1) when encountering the required `package.metadata.deb.systemd-units` header.

Described [here](https://github.com/mmstick/cargo-deb/issues/147) but it doesn't seem like anybody ever made an issue here.

Rebuilding the image should fix this.

A temporary workaround is to simply
```sh
cargo uninstall cargo-deb
cargo install cargo-deb
```
before using `cargo deb`.

Thanks for the otherwise excellent build image.

**Comment by gorup** [comment]
Hi! Thanks for this! I now will specify the version of cargo deb in the Dockerfile, so from now on if there is a new version it will be clear what is currently being used, and how to get to the latest version.

The build of this image takes a long time, but once its done I will publish a new version of this image. Thanks!

**Comment by gorup** [comment]
Built and tested, closing, let me know if you have any other questions!
